// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTTBaiThiLai.Migrations
{
    [DbContext(typeof(LTQLDb))]
    partial class LTQLDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DTTBaiThiLai.Models.DTT893", b =>
                {
                    b.Property<string>("HoTen")
                        .HasColumnType("TEXT");

                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("TEXT");

                    b.HasKey("HoTen");

                    b.ToTable("DTT893");
                });
#pragma warning restore 612, 618
        }
    }
}
